<?php

$gui = new \classes\Component\GUI();
$gui->opendiv('filt', 'col-xs-12 col-sm-6 col-md-5 col-lg-3');
    classes\Component\widget::executeWidgets(array(
       'usuario/group/widgets/userConfigGroupWidget' => array(),
    ));
$gui->closediv();

$gui->opendiv('filt', 'col-xs-12 col-sm-6 col-md-7 col-lg-9');
    classes\Component\widget::executeWidgets(array(
       'usuario/form/widgets/userConfigFormWidget' => array('formId'=>$form,'groupId'=>$group),
    ));
$gui->closediv();