<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:29.
 */
class log_usuarioWidgetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var log_usuarioWidget
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new log_usuarioWidget;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers log_usuarioWidget::mountWhere
     * @todo   Implement testMountWhere().
     */
    public function testMountWhere() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers log_usuarioWidget::setUser
     * @todo   Implement testSetUser().
     */
    public function testSetUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
