<?php

$this->LoadModel('usuario/login', 'uobj');
$user = $this->uobj->getUserNick($item, TRUE);
if(empty($user)) {
    $temp['user_name']  = "Usuário Anônimo";
    $temp['user_cargo'] = "";
}
else{
    $temp['user_name']  = $user['user_name'];
    $temp['user_cargo'] = $user['user_cargo'];
    $temp['cod_usuario'] = $user['cod_usuario'];
}

//$this->LoadComponent('usuario/login', 'logcomp')->show('usuario/login',$temp);
if($type == "" || empty($type)){
   if(false === getBoleanConstant('USUARIO_CORRETORA')) {
    $type = array('email', 'pessoal', 'senha', 'telefone', 'endereco');
   }
   else{
       $type = array('email', 'pessoal', 'senha', 'endereco');
   }
}

$this->LoadComponent('usuario/login/alterar', 'comp'); 
$class = (count($type) === 1)?'col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-5 col-ld-offset-5':"";
foreach($type as $t){
    if(!method_exists($this->comp, $t)){continue;}
    if($class !== ""){$this->comp->setClass($class);}
    call_user_func(array($this->comp, $t), $item);
}
