<?php

$gui = new \classes\Component\GUI();

$opt = array();


$gui->opendiv('', 'col-xs-12 panel panel-default');
    classes\Component\widget::executeWidgets(array(
        'usuario/acesso/widgets/pluginsReportWidget' => $opt
    ));
$gui->closediv();        
        
        
//$gui->opendiv('', 'col-xs-5');
//    classes\Component\widget::executeWidgets(array(
//        'carteira/carteira/widgets/createCarteiraReportWidget' => $opt,
//        'carteira/operacao/widgets/operacaoReportWidget' => $opt
//    ));
//$gui->closediv();
