<?php

$gui = new \classes\Component\GUI();

$opt = array();
$gui->opendiv('filt', 'col-xs-12');
    classes\Component\widget::executeWidgets(array(
        'usuario/acesso/widgets/dailyWidget' => $opt,
    ));
$gui->closediv();

$gui->opendiv('filt', 'col-xs-12 col-sm-6 col-md-5 col-lg-4 pull-right');
    classes\Component\widget::executeWidgets(array(
        'usuario/acesso/widgets/lastWidget' => $opt,
        'usuario/login/widgets/resumoWidget' => $opt,
    ));
$gui->closediv();
$gui->opendiv('filt', 'col-xs-12 col-sm-6 col-md-7 col-lg-8');
    classes\Component\widget::executeWidgets(array(
        'usuario/login/widgets/conversaoLoginWidget' => $opt,
        'usuario/acesso/widgets/conversaoAcessoWidget' => $opt,
        'usuario/acesso/widgets/actionAcessoWidget' => $opt,
    ));
$gui->closediv();

