<?php

$gui = new \classes\Component\GUI();

$opt = array('class' => 'span12');
$gui->opendiv('filt', 'span12');
    classes\Component\widget::executeWidgets(array(
        'usuario/acesso/widgets/dailyWidget' => $opt,
    ));
$gui->closediv();

$gui->opendiv('filt', 'span7');
    classes\Component\widget::executeWidgets(array(
        'usuario/login/widgets/conversaoLoginWidget' => $opt,
        'usuario/acesso/widgets/conversaoAcessoWidget' => $opt,
        'usuario/acesso/widgets/actionAcessoWidget' => $opt,
    ));
$gui->closediv();

$gui->opendiv('filt', 'span5 pull-right widget');
    classes\Component\widget::executeWidgets(array(
        'usuario/acesso/widgets/lastWidget' => $opt,
        'usuario/login/widgets/resumoWidget' => $opt,
    ));
$gui->closediv();
