<?php

$gui = new \classes\Component\GUI();
$gui->opendiv('filt', 'col-xs-12');
    classes\Component\widget::executeWidgets(array(
        'usuario/login/widgets/searchUserWidget' => array('class' => 'col-xs-12'),
        //'usuario/login/widgets/listUserWidget'   => $opt,
        'usuario/login/widgets/cadastrosWidget'  => array('class' => 'col-xs-12 pull-left'),
        'usuario/login/widgets/acessosWidget'    => array('class' => 'col-xs-12 pull-right'),
    ));
$gui->closediv();