<?php

$gui = new \classes\Component\GUI();

$opt = array('class' => 'col-xs-12');

$gui->opendiv('filt', 'col-xs-12');
    classes\Component\widget::executeWidgets(array(
        'usuario/login/widgets/searchUserWidget' => $opt,
        //'usuario/login/widgets/listUserWidget'   => $opt,
        'usuario/login/widgets/cadastrosWidget'  => $opt,
        'usuario/login/widgets/acessosWidget'    => $opt,
    ));
$gui->closediv();