
<div class="col-md-4 col-md-offset-2">
<h3>Confirme sua senha para prosseguir</h3>
<?php 
    $dados = $this->LoadModel('usuario/login', 'uobj')->getDados();
    $out   = array(
        'senha_login' => array(
            'name'     => 'Confirmar Senha',
            'notnull'  => 'true',
            'placeholder' => "Digite a sua senha",
            'especial' => 'senha',
            'button'   => array(
                'text' => 'Confirmar Senha', 
                'attrs'=>array('class'=>'btn btn-sucess')
             )
        )
    );
    $url = usuario_loginModel::getActualLink();
    $this->LoadResource("formulario", "form");
    $this->form->NewForm($out, array(), array(), $ajax = false, $url);
?>
</div>
