<?php 
    $clique = $this->Html->getLink('usuario/login/confirm_resend');
    $clique = "<a href='$clique'>clique aqui</a>"
?>
<hr/>
<h2>Porque devo confirmar minha conta?</h2>
<h4>Para enviar uma novo email de confirmação para sua conta <?php echo $clique; ?></h4>
<hr/>
<p>
    Para cada novidade no site a respeito da sua conta você pode receber notificações via email.
    Caso você tenha digitado um email errado ou sua conta de email esteja inativa você não receberá tais alertas.
</p>