<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:14.
 */
class listUserWidgetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var listUserWidget
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new listUserWidget;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
