<div class="span12 box-content" ng-controller="usuario_mensagemCTRL" style="height: 380px; overflow-y: scroll; overflow-x: auto; " >
    <div class="box span11" style="margin-top: 5px;" ng-repeat="msg in messages" ng-class="{read:(msg.visualizada === 's'), unread:(msg.visualizada === 'n' && msg.from !== user.cod_usuario)}">
        <div class="box-header"><a href="{{url}}/{{msg.cod_usuario}}" target="_BLANK">{{msg.from}}</a> - {{msg.data|fromNow}}</div>
        <div class="box-content">{{msg.mensagem}}</div>
    </div>
    
    <div ng-show="!messages.length">Nenhuma mensagem nesta conversa!</div>
</div>