<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:17.
 */
class usuario_loginDialogsModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var usuario_loginDialogsModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new usuario_loginDialogsModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers usuario_loginDialogsModel::setModelName
     * @todo   Implement testSetModelName().
     */
    public function testSetModelName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginDialogsModel::inserir
     * @todo   Implement testInserir().
     */
    public function testInserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginDialogsModel::resend_confirmation
     * @todo   Implement testResend_confirmation().
     */
    public function testResend_confirmation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginDialogsModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginDialogsModel::RecoverPassword
     * @todo   Implement testRecoverPassword().
     */
    public function testRecoverPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginDialogsModel::ConfirmRecoverPassword
     * @todo   Implement testConfirmRecoverPassword().
     */
    public function testConfirmRecoverPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
