<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:13.
 */
class loginComponentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var loginComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new loginComponent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers loginComponent::Subscribe
     * @todo   Implement testSubscribe().
     */
    public function testSubscribe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::tela_login
     * @todo   Implement testTela_login().
     */
    public function testTela_login() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::LoggedMenu
     * @todo   Implement testLoggedMenu().
     */
    public function testLoggedMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::menu
     * @todo   Implement testMenu().
     */
    public function testMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::setLoadMenu
     * @todo   Implement testSetLoadMenu().
     */
    public function testSetLoadMenu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::drawTitle
     * @todo   Implement testDrawTitle().
     */
    public function testDrawTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::getActionLinks
     * @todo   Implement testGetActionLinks().
     */
    public function testGetActionLinks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::format_user_criadoem
     * @todo   Implement testFormat_user_criadoem().
     */
    public function testFormat_user_criadoem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginComponent::format_user_uacesso
     * @todo   Implement testFormat_user_uacesso().
     */
    public function testFormat_user_uacesso() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
