<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:18.
 */
class loginFacebookTest extends PHPUnit_Framework_TestCase {

    /**
     * @var loginFacebook
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new loginFacebook;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers loginFacebook::setUserModel
     * @todo   Implement testSetUserModel().
     */
    public function testSetUserModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginFacebook::valida
     * @todo   Implement testValida().
     */
    public function testValida() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers loginFacebook::getFBLink
     * @todo   Implement testGetFBLink().
     */
    public function testGetFBLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
