<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:12.
 */
class usuario_loginModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var usuario_loginModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new usuario_loginModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers usuario_loginModel::atualizaStatus
     * @todo   Implement testAtualizaStatus().
     */
    public function testAtualizaStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::setLastAccessOfUser
     * @todo   Implement testSetLastAccessOfUser().
     */
    public function testSetLastAccessOfUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getDados
     * @todo   Implement testGetDados().
     */
    public function testGetDados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::IsLoged
     * @todo   Implement testIsLoged().
     */
    public function testIsLoged() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::Logout
     * @todo   Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::IsEnabledTutorial
     * @todo   Implement testIsEnabledTutorial().
     */
    public function testIsEnabledTutorial() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::disableTutorial
     * @todo   Implement testDisableTutorial().
     */
    public function testDisableTutorial() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::enableTutorial
     * @todo   Implement testEnableTutorial().
     */
    public function testEnableTutorial() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::userIsConfirmed
     * @todo   Implement testUserIsConfirmed().
     */
    public function testUserIsConfirmed() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::resend_confirmation
     * @todo   Implement testResend_confirmation().
     */
    public function testResend_confirmation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getCodUsuario
     * @todo   Implement testGetCodUsuario().
     */
    public function testGetCodUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getUserNick
     * @todo   Implement testGetUserNick().
     */
    public function testGetUserNick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getUserData
     * @todo   Implement testGetUserData().
     */
    public function testGetUserData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::Login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::inserir
     * @todo   Implement testInserir().
     */
    public function testInserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::editarDados
     * @todo   Implement testEditarDados().
     */
    public function testEditarDados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getAutenticatedUser
     * @todo   Implement testGetAutenticatedUser().
     */
    public function testGetAutenticatedUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::apagar
     * @todo   Implement testApagar().
     */
    public function testApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::Confirm
     * @todo   Implement testConfirm().
     */
    public function testConfirm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::RecoverPassword
     * @todo   Implement testRecoverPassword().
     */
    public function testRecoverPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::ConfirmRecoverPassword
     * @todo   Implement testConfirmRecoverPassword().
     */
    public function testConfirmRecoverPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::resend
     * @todo   Implement testResend().
     */
    public function testResend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::needWebmasterLogin
     * @todo   Implement testNeedWebmasterLogin().
     */
    public function testNeedWebmasterLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::needAdminLogin
     * @todo   Implement testNeedAdminLogin().
     */
    public function testNeedAdminLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::needLogin
     * @todo   Implement testNeedLogin().
     */
    public function testNeedLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::Redirect
     * @todo   Implement testRedirect().
     */
    public function testRedirect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getUserId
     * @todo   Implement testGetUserId().
     */
    public function testGetUserId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::Is
     * @todo   Implement testIs().
     */
    public function testIs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::IsWebmaster
     * @todo   Implement testIsWebmaster().
     */
    public function testIsWebmaster() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::UserIsWebmaster
     * @todo   Implement testUserIsWebmaster().
     */
    public function testUserIsWebmaster() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::UserIsAdmin
     * @todo   Implement testUserIsAdmin().
     */
    public function testUserIsAdmin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::LoadPerfil
     * @todo   Implement testLoadPerfil().
     */
    public function testLoadPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getCodPerfil
     * @todo   Implement testGetCodPerfil().
     */
    public function testGetCodPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getUsuariosPorPerfil
     * @todo   Implement testGetUsuariosPorPerfil().
     */
    public function testGetUsuariosPorPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getTotalUsuariosPorPerfil
     * @todo   Implement testGetTotalUsuariosPorPerfil().
     */
    public function testGetTotalUsuariosPorPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::isLogged
     * @todo   Implement testIsLogged().
     */
    public function testIsLogged() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::CodUsuario
     * @todo   Implement testCodUsuario().
     */
    public function testCodUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::CodPerfil
     * @todo   Implement testCodPerfil().
     */
    public function testCodPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::blockUser
     * @todo   Implement testBlockUser().
     */
    public function testBlockUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::unblockUser
     * @todo   Implement testUnblockUser().
     */
    public function testUnblockUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::isBloqued
     * @todo   Implement testIsBloqued().
     */
    public function testIsBloqued() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::permissoes_alteradas
     * @todo   Implement testPermissoes_alteradas().
     */
    public function testPermissoes_alteradas() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::has_permission_alterada
     * @todo   Implement testHas_permission_alterada().
     */
    public function testHas_permission_alterada() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::isUpdatedPermissions
     * @todo   Implement testIsUpdatedPermissions().
     */
    public function testIsUpdatedPermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::UserCanAlter
     * @todo   Implement testUserCanAlter().
     */
    public function testUserCanAlter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::paginate
     * @todo   Implement testPaginate().
     */
    public function testPaginate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getCountPerfil
     * @todo   Implement testGetCountPerfil().
     */
    public function testGetCountPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getOrigem
     * @todo   Implement testGetOrigem().
     */
    public function testGetOrigem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::getUltimosCadastros
     * @todo   Implement testGetUltimosCadastros().
     */
    public function testGetUltimosCadastros() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_loginModel::user_action_log
     * @todo   Implement testUser_action_log().
     */
    public function testUser_action_log() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
