<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:25.
 */
class perfilPermissionsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var perfilPermissions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new perfilPermissions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers perfilPermissions::getPerfilPermissions
     * @todo   Implement testGetPerfilPermissions().
     */
    public function testGetPerfilPermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers perfilPermissions::hasPermission
     * @todo   Implement testHasPermission().
     */
    public function testHasPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers perfilPermissions::RedirectIfHasPermission
     * @todo   Implement testRedirectIfHasPermission().
     */
    public function testRedirectIfHasPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers perfilPermissions::hasPermissionByName
     * @todo   Implement testHasPermissionByName().
     */
    public function testHasPermissionByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers perfilPermissions::isPublic
     * @todo   Implement testIsPublic().
     */
    public function testIsPublic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
