<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:24.
 */
class perfilPermissionsFormTest extends PHPUnit_Framework_TestCase {

    /**
     * @var perfilPermissionsForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new perfilPermissionsForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers perfilPermissionsForm::savePermissions
     * @todo   Implement testSavePermissions().
     */
    public function testSavePermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers perfilPermissionsForm::genarateForm
     * @todo   Implement testGenarateForm().
     */
    public function testGenarateForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
