<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:24.
 */
class usuario_perfilModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var usuario_perfilModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new usuario_perfilModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers usuario_perfilModel::setModelName
     * @todo   Implement testSetModelName().
     */
    public function testSetModelName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::getCodPerfil
     * @todo   Implement testGetCodPerfil().
     */
    public function testGetCodPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::getNamePerfil
     * @todo   Implement testGetNamePerfil().
     */
    public function testGetNamePerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::setDefaultPerfil
     * @todo   Implement testSetDefaultPerfil().
     */
    public function testSetDefaultPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::getDefaultPerfil
     * @todo   Implement testGetDefaultPerfil().
     */
    public function testGetDefaultPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::selecionar
     * @todo   Implement testSelecionar().
     */
    public function testSelecionar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::paginate
     * @todo   Implement testPaginate().
     */
    public function testPaginate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::editar
     * @todo   Implement testEditar().
     */
    public function testEditar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::inserir
     * @todo   Implement testInserir().
     */
    public function testInserir() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::apagar
     * @todo   Implement testApagar().
     */
    public function testApagar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::checkUserCanAlter
     * @todo   Implement testCheckUserCanAlter().
     */
    public function testCheckUserCanAlter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::checkPerfilIsOwnUser
     * @todo   Implement testCheckPerfilIsOwnUser().
     */
    public function testCheckPerfilIsOwnUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::hasPermissionByName
     * @todo   Implement testHasPermissionByName().
     */
    public function testHasPermissionByName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::hasPermission
     * @todo   Implement testHasPermission().
     */
    public function testHasPermission() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_perfilModel::getPathPerfil
     * @todo   Implement testGetPathPerfil().
     */
    public function testGetPathPerfil() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
