<?php

$gui = new \classes\Component\GUI();

$opt = array('class' => 'col-xs-12');

$gui->opendiv('filt', 'col-xs-4');
    classes\Component\widget::executeWidgets(array(
        'usuario/acesso/widgets/pagesWidget' => $opt,
    ));
$gui->closediv();

$gui->opendiv('filt', 'col-xs-4 pull-right');
    classes\Component\widget::executeWidgets(array(
        
    ));
$gui->closediv();



$gui->opendiv('filt', 'col-xs-4 pull-right');
    classes\Component\widget::executeWidgets(array(
        'usuario/acesso/widgets/errosWidget' => $opt,
    ));
$gui->closediv();
