<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:32.
 */
class usuario_acessoModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var usuario_acessoModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new usuario_acessoModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers usuario_acessoModel::saveLog
     * @todo   Implement testSaveLog().
     */
    public function testSaveLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_acessoModel::getChartData
     * @todo   Implement testGetChartData().
     */
    public function testGetChartData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_acessoModel::getChartDataUnique
     * @todo   Implement testGetChartDataUnique().
     */
    public function testGetChartDataUnique() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_acessoModel::getChartErrorData
     * @todo   Implement testGetChartErrorData().
     */
    public function testGetChartErrorData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers usuario_acessoModel::getChartGroupData
     * @todo   Implement testGetChartGroupData().
     */
    public function testGetChartGroupData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
