<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-29 at 09:10:31.
 */
class acessoComponentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var acessoComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new acessoComponent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers acessoComponent::format_action
     * @todo   Implement testFormat_action().
     */
    public function testFormat_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers acessoComponent::format_logname
     * @todo   Implement testFormat_logname().
     */
    public function testFormat_logname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers acessoComponent::format_data
     * @todo   Implement testFormat_data().
     */
    public function testFormat_data() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
