<div class="span12" ng-app="usuario_messageApp">
    <?php 
        
        $bowerComponents = array(
            'moment/min/moment.min','moment/locale/pt-br',
            'angular/angular.min',
            //'angucomplete/angucomplete'
            /*,'redactor/redactor/redactor.min', 'angular-redactor/angular-redactor'*/
        );
        $this->Html->LoadBowerComponent($bowerComponents);
        
        $location = \classes\Classes\Registered::getPluginLocationUrl('usuario')."/mensagem/js";
        $this->Html->LoadJs(array(
            "$location/app.js", "$location/sync.js",
            "$location/formulario.js", "$location/messages.js",
            "$location/users.js", "$location/talkWith.js"
        ), true);

    ?>
    <div class="span9 pull-right box-content">
        <?php
            require_once __DIR__.'/app/talkWith.phtml';
            require_once __DIR__.'/app/formulario.phtml';
            require_once __DIR__.'/app/messages.phtml';
        ?>
    </div>
    <div class="span3">
        <?php
            require_once __DIR__.'/app/users.phtml';
        ?>
        
        <div ng-controller="usuario_mensagem_syncCTRL"></div>
    </div>
    
    <style>
        .unread{
            border-left: 8px solid #f50000!important;
        }
        .read{
            border-left: 8px solid gray!important;
        }
        .sub-footer, .footer, .breadcrumb{
            display: none;
        }
        #conteudo {margin-bottom: 0px; padding-bottom: 0px;}
    </style>
</div>